"use client";
import Header from "@/Components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/Components/Footer/Footer";
import { MantineProvider } from "@mantine/core";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MantineProvider
      withGlobalStyles
      withNormalizeCSS
      withCSSVariables
      theme={{
        colorScheme: "light",
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Header></Header>
          {children} <Footer></Footer>
        </body>
    
      </html>
    </MantineProvider>
  );
}
