"use client";
import { Provider } from "react-redux";
import "./globals.css";
import { Inter } from "next/font/google";
import HeaderNav from "../app/Components/HeaderNav/HeaderNav";
import Footer from "../app/Components/Footer/Footer";
import store from "./redux/store/store";
import { MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FoodMood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS withCSSVariables>
      <html lang="en">
        <Provider store={store}>
          <body className={inter.className}>
            <HeaderNav></HeaderNav>
            {children}
            <Footer></Footer>
          </body>
        </Provider>
      </html>
    </MantineProvider>
  );
}
